language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
  - cd openeo-python-client
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
  - cd ..

script:
  - python ValidationEngine.py
  - python -m unittest
