language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
  - cd openeo-python-client
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
  - cd ..

script:
  - python ValidationEngine.py
  - python -m unittest

deploy:
  local_dir: 'reports'
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
